<Include>

<!-- Add Remove Properties -->

<!--
    <Property Id='ARPNOMODIFY'>1</Property>
    <Property Id='ARPNOREPAIR'>1</Property>
-->
    <Property Id='ARPCOMMENTS'>$(var.PRODUCT)</Property>
    <Property Id='ARPCONTACT'>Openfabrics Alliance www.OpenFabrics.org</Property>
    <Property Id='ARPURLINFOABOUT'>https://wiki.openfabrics.org/tiki-index.php?page=OpenIB%20Windows</Property>
    <Property Id='ARPHELPLINK'>https://wiki.openfabrics.org/tiki-index.php?page=Windows+FAQ</Property>
    <Property Id='ARPURLUPDATEINFO'>http://www.openfabrics.org/downloads/Windows/</Property>
    <Property Id='ARPPRODUCTICON'>openfabrics.ico</Property>

</Include>
