<Include>

    <Component Id="Docs" Guid="931C58EF-3759-4cf4-89CC-276C017305BB">

      <CreateFolder />

      <File Id="OFAlogo" DiskId="1"
              Name="openfabrics.gif"
              Source="..\..\openfabrics.gif" />

      <File Id="manual.htm" DiskId="1"
              Name="Manual.htm"
              Source="..\bin\Misc\Manual.htm" />

      <File Id="Relnotes" DiskId="1"
              Name="Release_notes.htm"
              Source="..\..\Release_notes.htm" />

      <File Id="command_window" DiskId="1"
              Name="Command Window.lnk"
              Source="..\..\$(var.ARCHP)\Command Window.lnk" Vital="yes" />

      <File Id="about.vbs" DiskId="1"
              Name="about.vbs"
              Source="..\..\about.vbs" />

      <File Id="about_OFED.txt" DiskId="1"
              Name="about-OFED.txt"
              Source="..\..\about-OFED.txt" />

    </Component>

</Include>
