<Include>

    <Component Id="cWinVerbsOFED"
               Guid="20916BB0-5E16-49bb-BE9F-3A202D760E72">

      <File Id="libibverbs.pdb" DiskId="1"
            Name="libibverbs.pdb"
            Source="..\bin\HCA\$(var.ARCH)\libibverbs.pdb" />

      <File Id="libibmad.pdb" DiskId="1"
            Name="libibmad.pdb"
            Source="..\bin\HCA\$(var.ARCH)\libibmad.pdb" />

      <File Id="libibumad.pdb" DiskId="1"
            Name="libibumad.pdb"
            Source="..\bin\HCA\$(var.ARCH)\libibumad.pdb" />

      <File Id="librdmacm.pdb" DiskId="1"
            Name="librdmacm.pdb"
            Source="..\bin\HCA\$(var.ARCH)\librdmacm.pdb" />

      <File Id="libibnetdisc.pdb" DiskId="1"
            Name="libibnetdisc.pdb"
            Source="..\bin\HCA\$(var.ARCH)\libibnetdisc.pdb" />

    </Component>

    <Component Id="cWinVerbsUApps"
              Guid="ECAB2829-AE65-4ef8-8214-9A89E5BBDB9A">

      <File Id="ibv_asyncwatch.exe" DiskId="1"
            Name="ibv_asyncwatch.exe"
            Source="..\bin\tools\$(var.ARCH)\release\ibv_asyncwatch.exe" />
      <File Id="ibv_asyncwatch.pdb" DiskId="1"
            Name="ibv_asyncwatch.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\ibv_asyncwatch.pdb" />
      <File Id="ibv_devinfo.exe" DiskId="1"
            Name="ibv_devinfo.exe"
            Source="..\bin\tools\$(var.ARCH)\release\ibv_devinfo.exe" />
      <File Id="ibv_devinfo.pdb" DiskId="1"
            Name="ibv_devinfo.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\ibv_devinfo.pdb" />
      <File Id="ibv_rc_pingpong.exe" DiskId="1"
            Name="ibv_rc_pingpong.exe"
            Source="..\bin\tools\$(var.ARCH)\release\ibv_rc_pingpong.exe" />
      <File Id="ibv_rc_pingpong.pdb" DiskId="1"
            Name="ibv_rc_pingpong.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\ibv_rc_pingpong.pdb" />
      <File Id="ibv_read_bw.exe" DiskId="1"
            Name="ibv_read_bw.exe"
            Source="..\bin\tools\$(var.ARCH)\release\ibv_read_bw.exe" />
      <File Id="ibv_read_bw.pdb" DiskId="1"
            Name="ibv_read_bw.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\ibv_read_bw.pdb" />
      <File Id="ibv_read_lat.exe" DiskId="1"
            Name="ibv_read_lat.exe"
            Source="..\bin\tools\$(var.ARCH)\release\ibv_read_lat.exe" />
      <File Id="ibv_read_lat.pdb" DiskId="1"
            Name="ibv_read_lat.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\ibv_read_lat.pdb" />
      <File Id="ibv_send_bw.exe" DiskId="1"
            Name="ibv_send_bw.exe"
            Source="..\bin\tools\$(var.ARCH)\release\ibv_send_bw.exe" />
      <File Id="ibv_send_bw.pdb" DiskId="1"
            Name="ibv_send_bw.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\ibv_send_bw.pdb" />
      <File Id="ibv_send_lat.exe" DiskId="1"
            Name="ibv_send_lat.exe"
            Source="..\bin\tools\$(var.ARCH)\release\ibv_send_lat.exe" />
      <File Id="ibv_send_lat.pdb" DiskId="1"
            Name="ibv_send_lat.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\ibv_send_lat.pdb" />
      <File Id="ibv_uc_pingpong.exe" DiskId="1"
            Name="ibv_uc_pingpong.exe"
            Source="..\bin\tools\$(var.ARCH)\release\ibv_uc_pingpong.exe" />
      <File Id="ibv_uc_pingpong.pdb" DiskId="1"
            Name="ibv_uc_pingpong.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\ibv_uc_pingpong.pdb" />
      <File Id="ibv_ud_pingpong.exe" DiskId="1"
            Name="ibv_ud_pingpong.exe"
            Source="..\bin\tools\$(var.ARCH)\release\ibv_ud_pingpong.exe" />
      <File Id="ibv_ud_pingpong.pdb" DiskId="1"
            Name="ibv_ud_pingpong.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\ibv_ud_pingpong.pdb" />
      <File Id="ibv_write_bw.exe" DiskId="1"
            Name="ibv_write_bw.exe"
            Source="..\bin\tools\$(var.ARCH)\release\ibv_write_bw.exe" />
      <File Id="ibv_write_bw.pdb" DiskId="1"
            Name="ibv_write_bw.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\ibv_write_bw.pdb" />
      <File Id="ibv_write_lat.exe" DiskId="1"
            Name="ibv_write_lat.exe"
            Source="..\bin\tools\$(var.ARCH)\release\ibv_write_lat.exe" />
      <File Id="ibv_write_lat.pdb" DiskId="1"
            Name="ibv_write_lat.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\ibv_write_lat.pdb" />

      <File Id="rdma_cmatose.exe" DiskId="1"
            Name="rdma_cmatose.exe"
            Source="..\bin\tools\$(var.ARCH)\release\rdma_cmatose.exe" />
      <File Id="rdma_cmatose.pdb" DiskId="1"
            Name="rdma_cmatose.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\rdma_cmatose.pdb" />
      <File Id="ibv_rdma_lat.exe" DiskId="1"
            Name="ibv_rdma_lat.exe"
            Source="..\bin\tools\$(var.ARCH)\release\ibv_rdma_lat.exe" />
      <File Id="ibv_rdma_lat.pdb" DiskId="1"
            Name="ibv_rdma_lat.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\ibv_rdma_lat.pdb" />
      <File Id="ibv_rdma_bw.exe" DiskId="1"
            Name="ibv_rdma_bw.exe"
            Source="..\bin\tools\$(var.ARCH)\release\ibv_rdma_bw.exe" />
      <File Id="ibv_rdma_bw.pdb" DiskId="1"
            Name="ibv_rdma_bw.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\ibv_rdma_bw.pdb" />

      <File Id="ibaddr.exe" DiskId="1"
            Name="ibaddr.exe"
            Source="..\bin\tools\$(var.ARCH)\release\ibaddr.exe" />
      <File Id="ibaddr.pdb" DiskId="1"
            Name="ibaddr.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\ibaddr.pdb" />
      <File Id="ibcacheedit.exe" DiskId="1"
            Name="ibcacheedit.exe"
            Source="..\bin\tools\$(var.ARCH)\release\ibcacheedit.exe" />
      <File Id="ibcacheedit.pdb" DiskId="1"
            Name="ibcacheedit.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\ibcacheedit.pdb" />
      <File Id="iblinkinfo.exe" DiskId="1"
            Name="iblinkinfo.exe"
            Source="..\bin\tools\$(var.ARCH)\release\iblinkinfo.exe" />
      <File Id="iblinkinfo.pdb" DiskId="1"
            Name="iblinkinfo.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\iblinkinfo.pdb" />
      <File Id="ibnetdiscover.exe" DiskId="1"
            Name="ibnetdiscover.exe"
            Source="..\bin\tools\$(var.ARCH)\release\ibnetdiscover.exe" />
      <File Id="ibnetdiscover.pdb" DiskId="1"
            Name="ibnetdiscover.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\ibnetdiscover.pdb" />
      <File Id="ibping.exe" DiskId="1"
            Name="ibping.exe"
            Source="..\bin\tools\$(var.ARCH)\release\ibping.exe" />
      <File Id="ibping.pdb" DiskId="1"
            Name="ibping.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\ibping.pdb" />
      <File Id="ibportstate.exe" DiskId="1"
            Name="ibportstate.exe"
            Source="..\bin\tools\$(var.ARCH)\release\ibportstate.exe" />
      <File Id="ibportstate.pdb" DiskId="1"
            Name="ibportstate.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\ibportstate.pdb" />
      <File Id="ibqueryerrors.exe" DiskId="1"
            Name="ibqueryerrors.exe"
            Source="..\bin\tools\$(var.ARCH)\release\ibqueryerrors.exe" />
      <File Id="ibqueryerrors.pdb" DiskId="1"
            Name="ibqueryerrors.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\ibqueryerrors.pdb" />
      <File Id="ibroute.exe" DiskId="1"
            Name="ibroute.exe"
            Source="..\bin\tools\$(var.ARCH)\release\ibroute.exe" />
      <File Id="ibroute.pdb" DiskId="1"
            Name="ibroute.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\ibroute.pdb" />
      <File Id="ibsendtrap.exe" DiskId="1"
            Name="ibsendtrap.exe"
            Source="..\bin\tools\$(var.ARCH)\release\ibsendtrap.exe" />
      <File Id="ibsendtrap.pdb" DiskId="1"
            Name="ibsendtrap.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\ibsendtrap.pdb" />
      <File Id="ibstat.exe" DiskId="1"
            Name="ibstat.exe"
            Source="..\bin\tools\$(var.ARCH)\release\ibstat.exe" />
      <File Id="ibstat.pdb" DiskId="1"
            Name="ibstat.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\ibstat.pdb" />
      <File Id="ibsysstat.exe" DiskId="1"
            Name="ibsysstat.exe"
            Source="..\bin\tools\$(var.ARCH)\release\ibsysstat.exe" />
      <File Id="ibsysstat.pdb" DiskId="1"
            Name="ibsysstat.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\ibsysstat.pdb" />
      <File Id="ibtracert.exe" DiskId="1"
            Name="ibtracert.exe"
            Source="..\bin\tools\$(var.ARCH)\release\ibtracert.exe" />
      <File Id="ibtracert.pdb" DiskId="1"
            Name="ibtracert.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\ibtracert.pdb" />
      <File Id="mcm_rereg_test.exe" DiskId="1"
            Name="mcm_rereg_test.exe"
            Source="..\bin\tools\$(var.ARCH)\release\mcm_rereg_test.exe" />
      <File Id="mcm_rereg_test.pdb" DiskId="1"
            Name="mcm_rereg_test.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\mcm_rereg_test.pdb" />
      <File Id="perfquery.exe" DiskId="1"
            Name="perfquery.exe"
            Source="..\bin\tools\$(var.ARCH)\release\perfquery.exe" />
      <File Id="perfquery.pdb" DiskId="1"
            Name="perfquery.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\perfquery.pdb" />
      <File Id="saquery.exe" DiskId="1"
            Name="saquery.exe"
            Source="..\bin\tools\$(var.ARCH)\release\saquery.exe" />
      <File Id="saquery.pdb" DiskId="1"
            Name="saquery.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\saquery.pdb" />
      <File Id="sminfo.exe" DiskId="1"
            Name="sminfo.exe"
            Source="..\bin\tools\$(var.ARCH)\release\sminfo.exe" />
      <File Id="sminfo.pdb" DiskId="1"
            Name="sminfo.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\sminfo.pdb" />
      <File Id="smpdump.exe" DiskId="1"
            Name="smpdump.exe"
            Source="..\bin\tools\$(var.ARCH)\release\smpdump.exe" />
      <File Id="smpdump.pdb" DiskId="1"
            Name="smpdump.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\smpdump.pdb" />
      <File Id="smpquery.exe" DiskId="1"
            Name="smpquery.exe"
            Source="..\bin\tools\$(var.ARCH)\release\smpquery.exe" />
      <File Id="smpquery.pdb" DiskId="1"
            Name="smpquery.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\smpquery.pdb" />
      <File Id="vendstat.exe" DiskId="1"
            Name="vendstat.exe"
            Source="..\bin\tools\$(var.ARCH)\release\vendstat.exe" />
      <File Id="vendstat.pdb" DiskId="1"
            Name="vendstat.pdb"
            Source="..\bin\tools\$(var.ARCH)\release\vendstat.pdb" />
    </Component>

    <?include $(sys.CURRENTDIR)\..\..\common\Rsockets.inc ?>

</Include>
