/*
 * [4-15-2010]
 *
 * files moved from SOURCES to here to decrease opensm.exe build time.
 * Reduced OpenSM.exe build time by 29 seconds.
 */

#include <main.c>
#include <osm_console.c>
#include <osm_console_io.c>
#include <osm_db_files.c>
#include <osm_helper.c>
#include <osm_db_pack.c>
#include <osm_drop_mgr.c>
#include <osm_dump.c>
#include <osm_event_plugin.c>
#include <osm_inform.c>
#include <osm_lid_mgr.c>
#include <osm_link_mgr.c>
#include <osm_lin_fwd_rcv.c>
#include <osm_log.c>
#include <osm_mad_pool.c>
#include <osm_mcast_fwd_rcv.c>
#include <osm_mcast_mgr.c>
#include <osm_mcast_tbl.c>
#include <osm_mcm_port.c>
#include <osm_mesh.c>
#include <osm_mlnx_ext_port_info_rcv.c>
#include <osm_mtree.c>
#include <osm_multicast.c>
#include <osm_node.c>
#include <osm_node_desc_rcv.c>
#include <osm_node_info_rcv.c>
#include <osm_opensm.c>
#include <osm_perfmgr.c>
#include <osm_perfmgr_db.c>
#include <osm_pkey.c>
#include <osm_pkey_mgr.c>
#include <osm_pkey_rcv.c>
#include <osm_port.c>
#include <osm_port_info_rcv.c>
#include <osm_prtn.c>
#include <osm_prtn_config.c>
#include <osm_qos.c>
#include <osm_qos_policy.c>
#include <osm_remote_sm.c>
#include <osm_req.c>
#include <osm_resp.c>
#include <osm_router.c>
#include <osm_sa.c>
#include <osm_sa_class_port_info.c>
#include <osm_sa_guidinfo_record.c>
#include <osm_sa_informinfo.c>
#include <osm_sa_lft_record.c>
#include <osm_sa_link_record.c>
#include <osm_sa_mad_ctrl.c>
#include <osm_sa_mft_record.c>
#include <osm_sa_multipath_record.c>
#include <osm_sa_node_record.c>
#include <osm_sa_pkey_record.c>
#include <osm_sa_portinfo_record.c>
#include <osm_sa_service_record.c>
#include <osm_sa_slvl_record.c>
#include <osm_sa_sminfo_record.c>
#include <osm_sa_sw_info_record.c>
#include <osm_sa_vlarb_record.c>
#include <osm_service.c>
#include <osm_slvl_map_rcv.c>
#include <osm_sm.c>
#include <osm_sminfo_rcv.c>
#include <osm_sm_mad_ctrl.c>
#include <osm_sm_state_mgr.c>
#include <osm_state_mgr.c>
#include <osm_subnet.c>
#include <osm_switch.c>
#include <osm_sw_info_rcv.c>
#include <osm_torus.c>
#include <osm_trap_rcv.c>
#include <osm_ucast_cache.c>
#include <osm_ucast_file.c>
#include <osm_ucast_ftree.c>
#include <osm_ucast_lash.c>
#include <osm_ucast_mgr.c>
#include <osm_ucast_updn.c>
#include <osm_vl15intf.c>
#include <osm_vl_arb_rcv.c>
#include <st.c>
#include "../../../../etc/user/gtod.c"

